# Generated by Django 6.1 on 2026-08-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('admin', 'Admin')], default='host', help_text='host = manages their own organization; admin = platform app management', max_length=16),
        ),
    ]
