# Generated by Django 6.1 on 2026-08-11 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('meeting_date', models.DateField()),
                ('meeting_type', models.CharField(choices=[('meeting', 'Meeting'), ('one_on_one', 'One-on-One'), ('standup', 'Standup'), ('brainstorm', 'Brainstorm'), ('review', 'Review'), ('client_call', 'Client Call'), ('other', 'Other')], default='meeting', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('transcript_path', models.CharField(blank=True, default='', max_length=1024)),
                ('transcript_filename', models.CharField(blank=True, default='', max_length=255)),
                ('audio_path', models.CharField(blank=True, default='', max_length=1024)),
                ('audio_filename', models.CharField(blank=True, default='', max_length=255)),
                ('pdf_path', models.CharField(blank=True, default='', max_length=1024)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('review_required', 'Review Required'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=32)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='organizations.organization')),
            ],
            options={
                'ordering': ['-meeting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_points', to='meetings.meeting')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='meetings.meeting')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_links', to='meetings.meeting')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_links', to='people.person')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('paragraph_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='meetings.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='PersonMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('context', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='meetings.meeting')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to='people.person')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organization', 'status'], name='meetings_me_organiz_5cee97_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organization', 'meeting_date'], name='meetings_me_organiz_5f9aae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingparticipant',
            unique_together={('meeting', 'person')},
        ),
        migrations.AddIndex(
            model_name='personmention',
            index=models.Index(fields=['meeting', 'person'], name='meetings_pe_meeting_e0c919_idx'),
        ),
    ]
