# Generated by Django 6.1 on 2026-08-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='processing_stage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
