# Generated by Django 6.1 on 2026-08-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='teams',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
