# Generated by Django 6.1 on 2026-08-11 05:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mentioned_name', models.CharField(blank=True, default='', max_length=255)),
                ('task', models.CharField(max_length=1000)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('context', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('ai', 'AI'), ('manual', 'Manual')], default='ai', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='meetings.meeting')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['meeting', 'person'], name='tasks_task_meeting_d4d95d_idx'), models.Index(fields=['meeting', 'status'], name='tasks_task_meeting_f334ee_idx')],
            },
        ),
    ]
