# Generated by Django 4.2.30 on 2026-09-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
