# Generated by Django 6.1 on 2026-08-11 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(blank=True, default='', help_text='Main brand color (hex, e.g. #2563eb). Empty = default blue.', max_length=7)),
                ('accent_color', models.CharField(blank=True, default='', help_text='Accent / gradient partner color (hex, e.g. #0ea5e9).', max_length=7)),
                ('light_background', models.CharField(blank=True, default='', help_text='Light-mode background (hex). Empty = default white.', max_length=7)),
                ('dark_background', models.CharField(blank=True, default='', help_text='Dark-mode background (hex). Empty = default slate.', max_length=7)),
                ('radius', models.CharField(choices=[('0.5rem', 'Soft'), ('0.75rem', 'Rounded (default)'), ('1rem', 'Extra rounded'), ('0rem', 'Sharp')], default='0.75rem', help_text='Corner radius of cards, buttons and inputs.', max_length=8)),
                ('font_family', models.CharField(choices=[('default', 'Default (Geist)'), ('system', 'System UI'), ('serif', 'Elegant Serif'), ('mono', 'Monospace')], default='default', help_text='Body font family. Headings always keep the Saira Condensed display font.', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site theme',
                'verbose_name_plural': 'Site themes',
            },
        ),
    ]
