"use client";

import { useState } from "react";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import {
  CalendarDays,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Download,
  Eye,
  FileBarChart2,
  FileDown,
  Loader2,
  ListChecks,
  Users,
} from "lucide-react";
import { toast } from "sonner";

import { PageHeader } from "@/components/shared/page-header";
import { EmptyState } from "@/components/shared/empty-state";
import { ErrorState } from "@/components/shared/error-state";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { api } from "@/lib/api";
import { reportsService } from "@/services/reports";
import { formatDateTime, getErrorMessage } from "@/lib/utils";
import type { MeetingReport } from "@/types";

export default function ReportsPage() {
  const [page, setPage] = useState(1);
  const [downloading, setDownloading] = useState<string | null>(null);

  const query = useQuery({
    queryKey: ["reports", page],
    queryFn: () => reportsService.list(page),
  });

  const download = async (report: MeetingReport) => {
    setDownloading(report.id);
    try {
      const { url } = await reportsService.downloadUrl(report.id);
      if (url.startsWith("http")) {
        window.open(url, "_blank", "noopener");
      } else {
        const blob = await api.fetchBlob(url);
        const objectUrl = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = objectUrl;
        link.download = `IntelliConnect-${report.meeting_title.replace(/[^\w-]+/g, "-")}.pdf`;
        link.click();
        URL.revokeObjectURL(objectUrl);
      }
      toast.success("Report downloaded.");
    } catch (error) {
      toast.error(getErrorMessage(error, "We couldn't download this report."));
    } finally {
      setDownloading(null);
    }
  };

  const view = async (report: MeetingReport) => {
    try {
      const { url } = await reportsService.downloadUrl(report.id);
      if (url.startsWith("http")) {
        window.open(url, "_blank", "noopener");
      } else {
        const blob = await api.fetchBlob(url);
        const objectUrl = URL.createObjectURL(blob);
        window.open(objectUrl, "_blank", "noopener");
        setTimeout(() => URL.revokeObjectURL(objectUrl), 60_000);
      }
    } catch (error) {
      toast.error(getErrorMessage(error, "We couldn't open this report."));
    }
  };

  const data = query.data;
  const reports = data?.results ?? [];

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports"
        description="Professional PDF meeting reports generated by IntelliConnect."
      />

      {query.isError && <ErrorState message={(query.error as Error).message} onRetry={() => query.refetch()} />}

      {query.isLoading && (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {Array.from({ length: 6 }).map((_, i) => (
            <Skeleton key={i} className="h-40 w-full" />
          ))}
        </div>
      )}

      {!query.isLoading && !query.isError && data && data.count === 0 && (
        <EmptyState
          icon={FileBarChart2}
          title="No reports yet"
          description="Generate your first report from a completed meeting and it will appear here, ready to share."
          action={
            <Button asChild variant="gradient">
              <Link href="/meetings">
                <FileDown className="h-4 w-4" aria-hidden="true" /> Go to Meetings
              </Link>
            </Button>
          }
        />
      )}

      {!query.isLoading && !query.isError && data && data.count > 0 && (
        <>
          {/* Desktop table */}
          <div className="hidden overflow-hidden rounded-xl border border-border bg-card shadow-[var(--shadow-card)] md:block">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Meeting</TableHead>
                  <TableHead>Meeting Date</TableHead>
                  <TableHead>Generated</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-center">Tasks</TableHead>
                  <TableHead className="text-center">Decisions</TableHead>
                  <TableHead className="w-28">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {reports.map((report) => (
                  <TableRow key={report.id}>
                    <TableCell>
                      <Link href={`/meetings/${report.meeting}`} className="font-medium text-foreground hover:text-primary">
                        {report.meeting_title}
                      </Link>
                    </TableCell>
                    <TableCell className="whitespace-nowrap text-muted-foreground">
                      {formatDateTime(report.meeting_date)}
                    </TableCell>
                    <TableCell className="whitespace-nowrap text-muted-foreground">
                      {formatDateTime(report.generated_at)}
                    </TableCell>
                    <TableCell>
                      {report.status === "ready" ? (
                        <Badge variant="success"><CheckCircle2 className="h-3 w-3" aria-hidden="true" /> Ready</Badge>
                      ) : report.status === "generating" ? (
                        <Badge variant="violet"><Loader2 className="h-3 w-3 animate-spin" aria-hidden="true" /> Generating</Badge>
                      ) : (
                        <Badge variant="danger">Failed</Badge>
                      )}
                    </TableCell>
                    <TableCell className="text-center">{report.tasks_count}</TableCell>
                    <TableCell className="text-center">{report.decisions_count}</TableCell>
                    <TableCell>
                      <div className="flex gap-1">
                        <Button variant="ghost" size="iconSm" onClick={() => view(report)} aria-label={`View report for ${report.meeting_title}`}>
                          <Eye className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="iconSm"
                          onClick={() => download(report)}
                          disabled={downloading === report.id}
                          aria-label={`Download report for ${report.meeting_title}`}
                        >
                          {downloading === report.id ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>

          {/* Mobile cards */}
          <div className="space-y-3 md:hidden">
            {reports.map((report) => (
              <Card key={report.id}>
                <CardContent className="p-4">
                  <div className="flex items-start justify-between gap-2">
                    <Link href={`/meetings/${report.meeting}`} className="font-medium text-foreground hover:text-primary">
                      {report.meeting_title}
                    </Link>
                    {report.status === "ready" ? (
                      <Badge variant="success"><CheckCircle2 className="h-3 w-3" aria-hidden="true" /> Ready</Badge>
                    ) : (
                      <Badge variant="violet"><Loader2 className="h-3 w-3 animate-spin" aria-hidden="true" /> Generating</Badge>
                    )}
                  </div>
                  <div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-1.5 text-xs text-muted-foreground">
                    <span className="inline-flex items-center gap-1"><CalendarDays className="h-3 w-3" aria-hidden="true" /> {formatDateTime(report.meeting_date)}</span>
                    <span>Generated {formatDateTime(report.generated_at)}</span>
                    <span className="inline-flex items-center gap-1"><ListChecks className="h-3 w-3" aria-hidden="true" /> {report.tasks_count} tasks</span>
                    <span className="inline-flex items-center gap-1"><Users className="h-3 w-3" aria-hidden="true" /> {report.decisions_count} decisions</span>
                  </div>
                  <div className="mt-3 flex gap-2">
                    <Button size="sm" variant="outline" className="flex-1" onClick={() => view(report)}>
                      <Eye className="h-3.5 w-3.5" aria-hidden="true" /> View
                    </Button>
                    <Button size="sm" variant="outline" className="flex-1" onClick={() => download(report)} disabled={downloading === report.id}>
                      {downloading === report.id ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" aria-hidden="true" />}
                      Download
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          {data.total_pages > 1 && (
            <div className="flex items-center justify-end gap-2">
              <Button variant="outline" size="sm" disabled={page <= 1} onClick={() => setPage((p) => p - 1)} aria-label="Previous page">
                <ChevronLeft className="h-4 w-4" />
              </Button>
              <span className="text-sm text-muted-foreground">Page {data.page} of {data.total_pages}</span>
              <Button variant="outline" size="sm" disabled={page >= data.total_pages} onClick={() => setPage((p) => p + 1)} aria-label="Next page">
                <ChevronRight className="h-4 w-4" />
              </Button>
            </div>
          )}
        </>
      )}
    </div>
  );
}
