"""Professional meeting report generation.

Produces a polished corporate PDF with:
  * Cover page — IntelliConnect branding band, meeting title, meta grid
  * Executive Summary
  * Key Discussion Points
  * Decisions
  * Participants
  * Assigned Tasks (person | department | task | deadline | status)
  * People Mentioned
  * Transcript (speaker turns, when available)
  * Footer — generated timestamp + page numbers
"""

import html
import io
from datetime import date, datetime, timezone

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from meetings.models import Meeting, MeetingParticipant

# ---------------------------------------------------------------------------
# Brand palette (mirrors the product's visual identity — blue → sky)
# ---------------------------------------------------------------------------

BLUE = colors.HexColor("#2563EB")
SKY = colors.HexColor("#0EA5E9")
INK = colors.HexColor("#0F172A")
SLATE = colors.HexColor("#475569")
LIGHT = colors.HexColor("#F1F5F9")
LIGHTER = colors.HexColor("#F8FAFC")
BORDER = colors.HexColor("#E2E8F0")
EMERALD = colors.HexColor("#059669")
AMBER = colors.HexColor("#B45309")

_PAGE_W, _PAGE_H = A4
_MARGIN = 18 * mm


def _styles():
    base = getSampleStyleSheet()
    styles = {
        "CoverBrand": ParagraphStyle(
            "CoverBrand", parent=base["Normal"], fontName="Helvetica-Bold",
            fontSize=20, leading=24, textColor=colors.white,
        ),
        "CoverTag": ParagraphStyle(
            "CoverTag", parent=base["Normal"], fontName="Helvetica",
            fontSize=10, leading=13, textColor=colors.white,
        ),
        "CoverTitle": ParagraphStyle(
            "CoverTitle", parent=base["Normal"], fontName="Helvetica-Bold",
            fontSize=28, leading=34, textColor=INK, spaceBefore=18,
        ),
        "CoverMetaLabel": ParagraphStyle(
            "CoverMetaLabel", parent=base["Normal"], fontName="Helvetica-Bold",
            fontSize=8.5, leading=11, textColor=SLATE,
        ),
        "CoverMetaValue": ParagraphStyle(
            "CoverMetaValue", parent=base["Normal"], fontName="Helvetica",
            fontSize=11, leading=15, textColor=INK,
        ),
        "H1": ParagraphStyle(
            "H1", parent=base["Normal"], fontName="Helvetica-Bold",
            fontSize=15, leading=19, textColor=BLUE, spaceBefore=12, spaceAfter=4,
        ),
        "Body": ParagraphStyle(
            "Body", parent=base["Normal"], fontName="Helvetica",
            fontSize=10.5, leading=15, textColor=INK, alignment=TA_LEFT,
        ),
        "Bullet": ParagraphStyle(
            "Bullet", parent=base["Normal"], fontName="Helvetica",
            fontSize=10.5, leading=15, textColor=INK, leftIndent=12, bulletIndent=2,
        ),
        "TurnSpeaker": ParagraphStyle(
            "TurnSpeaker", parent=base["Normal"], fontName="Helvetica-Bold",
            fontSize=9.5, leading=13, textColor=BLUE, spaceBefore=5,
        ),
        "TurnText": ParagraphStyle(
            "TurnText", parent=base["Normal"], fontName="Helvetica",
            fontSize=9.5, leading=13.5, textColor=INK, leftIndent=2,
        ),
        "TaskCell": ParagraphStyle(
            "TaskCell", parent=base["Normal"], fontName="Helvetica",
            fontSize=9, leading=12.5, textColor=INK,
        ),
        "HeaderCell": ParagraphStyle(
            "HeaderCell", parent=base["Normal"], fontName="Helvetica-Bold",
            fontSize=9, leading=12.5, textColor=colors.white,
        ),
        "Footer": ParagraphStyle(
            "Footer", parent=base["Normal"], fontName="Helvetica",
            fontSize=8.5, leading=12, textColor=SLATE, alignment=TA_CENTER,
        ),
    }
    return styles


def _header_footer(canvas, doc):
    """Branded footer on every page after the cover."""
    canvas.saveState()
    if doc.page > 1:
        canvas.setFont("Helvetica", 8.5)
        canvas.setFillColor(SLATE)
        canvas.drawCentredString(_PAGE_W / 2, 12 * mm, "Generated by IntelliConnect")
        canvas.drawCentredString(
            _PAGE_W / 2, 8 * mm,
            f"Page {doc.page} · {datetime.now(timezone.utc):%B %d, %Y}",
        )
    canvas.restoreState()


def _section_header(story, styles, title):
    story.append(Paragraph(html.escape(title), styles["H1"]))
    story.append(HRFlowable(width="100%", thickness=2.5, color=BLUE, spaceBefore=0, spaceAfter=8))


def _escape(value: str) -> str:
    return html.escape(value or "")


def _transcript_blocks(meeting):
    """Read the stored transcript and split it into speaker turns.

    Failures are silent — a transcript section is optional and should
    never block report generation.
    """
    try:
        from storage import get_storage
        from meetings.transcripts import extract_transcript_text, parse_transcript_turns

        if not meeting.transcript_path:
            return None, False
        raw = get_storage().read(meeting.transcript_path)
        content = extract_transcript_text(meeting.transcript_filename or "transcript.txt", raw)
        turns, has_speakers = parse_transcript_turns(content)
        return turns, has_speakers
    except Exception:
        return None, False


def generate_meeting_pdf(meeting: Meeting, org_name: str = "") -> bytes:
    """Build the PDF bytes for a meeting."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=_MARGIN,
        rightMargin=_MARGIN,
        topMargin=_MARGIN,
        bottomMargin=_MARGIN,
        title=f"{meeting.title} — IntelliConnect Meeting Report",
        author="IntelliConnect",
    )
    styles = _styles()
    story = []

    # ------------------------------------------------------------------ cover
    # Branding band
    band_data = [[
        Paragraph("IntelliConnect", styles["CoverBrand"]),
        Paragraph("MEETING REPORT", styles["CoverTag"]),
    ]]
    band = Table(band_data, colWidths=[120 * mm, 60 * mm])
    band.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BLUE),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (1, 0), (1, 0), "RIGHT"),
    ]))
    story.append(band)
    story.append(Spacer(1, 10 * mm))

    story.append(Paragraph(_escape(meeting.title), styles["CoverTitle"]))
    story.append(HRFlowable(width="100%", thickness=0.8, color=BORDER, spaceBefore=2, spaceAfter=8))
    story.append(Spacer(1, 6 * mm))

    org = org_name or (meeting.organization.name if meeting.organization else "")
    meta_rows = [
        [
            Paragraph("DATE", styles["CoverMetaLabel"]),
            Paragraph(f"{meeting.meeting_date:%B %d, %Y}", styles["CoverMetaValue"]),
            Paragraph("ORGANIZATION", styles["CoverMetaLabel"]),
            Paragraph(_escape(org), styles["CoverMetaValue"]),
        ],
        [
            Paragraph("HOST", styles["CoverMetaLabel"]),
            Paragraph(_escape(meeting.host.full_name if meeting.host_id else "—"), styles["CoverMetaValue"]),
            Paragraph("MEETING TYPE", styles["CoverMetaLabel"]),
            Paragraph(_escape(meeting.get_meeting_type_display()), styles["CoverMetaValue"]),
        ],
    ]
    meta = Table(meta_rows, colWidths=[30 * mm, 50 * mm, 35 * mm, 65 * mm])
    meta.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHTER),
        ("BOX", (0, 0), (-1, -1), 0.6, BORDER),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(meta)
    story.append(Spacer(1, 8 * mm))

    participants = [
        link.person for link in MeetingParticipant.objects.filter(meeting=meeting)
        .select_related("person")
    ]
    if participants:
        story.append(
            Paragraph(
                f"<b>Participants:</b> {_escape(', '.join(p.full_name for p in participants))}",
                styles["Body"],
            )
        )
        story.append(Spacer(1, 6 * mm))

    story.append(PageBreak())

    # ------------------------------------------------------------ exec summary
    _section_header(story, styles, "Executive Summary")
    summary_text = meeting.summary.paragraph_summary if meeting.summary else ""
    if meeting.summary and meeting.summary.summary:
        story.append(
            Paragraph(
                f"<b>{_escape(meeting.summary.summary)}</b>",
                styles["Body"],
            )
        )
        story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(_escape(summary_text) or "No summary was generated for this meeting.", styles["Body"]))
    story.append(Spacer(1, 6 * mm))

    # ------------------------------------------------------------- key points
    key_points = list(meeting.key_points.all())
    if key_points:
        _section_header(story, styles, "Key Discussion Points")
        for index, point in enumerate(key_points, start=1):
            story.append(Paragraph(_escape(point.content), styles["Bullet"], bulletText=f"{index}."))
        story.append(Spacer(1, 6 * mm))

    # ---------------------------------------------------------------- decisions
    decisions = list(meeting.decisions.all())
    if decisions:
        _section_header(story, styles, "Decisions")
        for decision in decisions:
            story.append(Paragraph(_escape(decision.content), styles["Bullet"], bulletText="✓"))
        story.append(Spacer(1, 6 * mm))

    # ------------------------------------------------------------ assigned tasks
    tasks = list(meeting.tasks.select_related("person").all())
    _section_header(story, styles, "Assigned Tasks")
    if tasks:
        header = [Paragraph(h, styles["HeaderCell"]) for h in
                  ("Person", "Department", "Task", "Deadline", "Status")]
        rows = [header]
        for task in tasks:
            person = task.person.full_name if task.person else (task.mentioned_name or "Unassigned")
            department = task.person.department if task.person and task.person.department else "—"
            deadline = task.deadline.strftime("%b %d, %Y") if task.deadline else "—"
            rows.append([
                Paragraph(_escape(person), styles["TaskCell"]),
                Paragraph(_escape(department), styles["TaskCell"]),
                Paragraph(_escape(task.task), styles["TaskCell"]),
                Paragraph(deadline, styles["TaskCell"]),
                Paragraph(_escape(task.get_status_display()), styles["TaskCell"]),
            ])
        table = Table(rows, colWidths=[36 * mm, 32 * mm, 62 * mm, 28 * mm, 22 * mm], repeatRows=1)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), BLUE),
                    ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        story.append(table)
    else:
        story.append(Paragraph("No tasks were assigned in this meeting.", styles["Body"]))
    story.append(Spacer(1, 6 * mm))

    # ------------------------------------------------------------- mentions
    mentions = list(meeting.mentions.select_related("person").all())
    if mentions:
        _section_header(story, styles, "People Mentioned")
        for mention in mentions:
            resolved = mention.person.full_name if mention.person else f"{mention.full_name} (unresolved)"
            story.append(Paragraph(f"• {_escape(resolved)}", styles["Bullet"]))
        story.append(Spacer(1, 6 * mm))

    # ------------------------------------------------------------- transcript
    turns, has_speakers = _transcript_blocks(meeting)
    if turns:
        _section_header(story, styles, "Transcript")
        for turn in turns:
            speaker = turn["speaker"] if turn["speaker"] else "Speaker"
            if has_speakers:
                story.append(Paragraph(_escape(speaker), styles["TurnSpeaker"]))
                for line in turn["text"].splitlines():
                    if line.strip():
                        story.append(Paragraph(_escape(line), styles["TurnText"]))
            else:
                for line in turn["text"].splitlines():
                    if line.strip():
                        story.append(Paragraph(_escape(line), styles["Body"]))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buffer.getvalue()
