"""Professional meeting report generation.

Produces a polished corporate PDF with:
  * Cover header — IntelliConnect branding, meeting title, date, organization
  * Executive Summary
  * Key Discussion Points
  * Decisions
  * Participants
  * Assigned Tasks (person | department | task | deadline | status)
  * Footer — "Generated by IntelliConnect"
"""

import io
from datetime import date

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from meetings.models import Meeting, MeetingParticipant, PersonMention
from tasks.models import Task

# ---------------------------------------------------------------------------
# Brand palette (mirrors the product's visual identity)
# ---------------------------------------------------------------------------

INDIGO = colors.HexColor("#4F46E5")
VIOLET = colors.HexColor("#7C3AED")
INK = colors.HexColor("#0F172A")
SLATE = colors.HexColor("#475569")
LIGHT = colors.HexColor("#F1F5F9")
BORDER = colors.HexColor("#E2E8F0")
EMERALD = colors.HexColor("#059669")
AMBER = colors.HexColor("#B45309")

_PAGE_W, _PAGE_H = A4
_MARGIN = 18 * mm


def _styles():
    base = getSampleStyleSheet()
    styles = {
        "CoverBrand": ParagraphStyle(
            "CoverBrand", parent=base["Normal"], fontName="Helvetica-Bold",
            fontSize=22, leading=26, textColor=INDIGO,
        ),
        "CoverTitle": ParagraphStyle(
            "CoverTitle", parent=base["Normal"], fontName="Helvetica-Bold",
            fontSize=30, leading=36, textColor=INK, spaceBefore=6,
        ),
        "CoverMeta": ParagraphStyle(
            "CoverMeta", parent=base["Normal"], fontName="Helvetica",
            fontSize=12, leading=18, textColor=SLATE,
        ),
        "H1": ParagraphStyle(
            "H1", parent=base["Normal"], fontName="Helvetica-Bold",
            fontSize=16, leading=20, textColor=INK, spaceBefore=10, spaceAfter=6,
        ),
        "Body": ParagraphStyle(
            "Body", parent=base["Normal"], fontName="Helvetica",
            fontSize=10.5, leading=15, textColor=INK, alignment=TA_LEFT,
        ),
        "Bullet": ParagraphStyle(
            "Bullet", parent=base["Normal"], fontName="Helvetica",
            fontSize=10.5, leading=15, textColor=INK, leftIndent=12, bulletIndent=2,
        ),
        "TaskCell": ParagraphStyle(
            "TaskCell", parent=base["Normal"], fontName="Helvetica",
            fontSize=9.5, leading=13, textColor=INK,
        ),
        "HeaderCell": ParagraphStyle(
            "HeaderCell", parent=base["Normal"], fontName="Helvetica-Bold",
            fontSize=9.5, leading=13, textColor=colors.white,
        ),
        "Footer": ParagraphStyle(
            "Footer", parent=base["Normal"], fontName="Helvetica",
            fontSize=8.5, leading=12, textColor=SLATE, alignment=TA_CENTER,
        ),
    }
    return styles


def _header_footer(canvas, doc):
    """Branded footer on every page after the cover."""
    canvas.saveState()
    if doc.page > 1:
        canvas.setFont("Helvetica", 8.5)
        canvas.setFillColor(SLATE)
        canvas.drawCentredString(_PAGE_W / 2, 12 * mm, "Generated by IntelliConnect")
        canvas.drawCentredString(_PAGE_W / 2, 8 * mm, f"Page {doc.page}")
    canvas.restoreState()


def generate_meeting_pdf(meeting: Meeting, org_name: str = "") -> bytes:
    """Build the PDF bytes for a meeting."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=_MARGIN,
        rightMargin=_MARGIN,
        topMargin=_MARGIN,
        bottomMargin=_MARGIN,
        title=f"{meeting.title} — IntelliConnect Meeting Report",
        author="IntelliConnect",
    )
    styles = _styles()
    story = []

    # ------------------------------------------------------------------ cover
    story.append(Paragraph("IntelliConnect", styles["CoverBrand"]))
    story.append(Spacer(1, 2 * mm))
    story.append(HRFlowable(width="100%", thickness=1.5, color=INDIGO, spaceBefore=2, spaceAfter=10))
    story.append(Paragraph("Meeting Report", styles["CoverMeta"]))
    story.append(Paragraph(meeting.title, styles["CoverTitle"]))
    story.append(Spacer(1, 8 * mm))
    story.append(
        Paragraph(
            f"Date: <b>{meeting.meeting_date:%B %d, %Y}</b> &nbsp;|&nbsp; "
            f"Organization: <b>{org_name or meeting.organization.name}</b>",
            styles["CoverMeta"],
        )
    )
    if meeting.host_id:
        story.append(
            Paragraph(f"Host: <b>{meeting.host.full_name}</b>", styles["CoverMeta"])
        )
    story.append(PageBreak())

    # ------------------------------------------------------------ exec summary
    story.append(Paragraph("Executive Summary", styles["H1"]))
    story.append(HRFlowable(width="100%", thickness=0.8, color=BORDER, spaceAfter=6))
    summary_text = meeting.summary.paragraph_summary if meeting.summary else ""
    story.append(Paragraph(summary_text or "No summary was generated for this meeting.", styles["Body"]))
    story.append(Spacer(1, 6 * mm))

    # ------------------------------------------------------------- key points
    key_points = list(meeting.key_points.all())
    if key_points:
        story.append(Paragraph("Key Discussion Points", styles["H1"]))
        story.append(HRFlowable(width="100%", thickness=0.8, color=BORDER, spaceAfter=6))
        for index, point in enumerate(key_points, start=1):
            story.append(Paragraph(point.content, styles["Bullet"], bulletText=f"{index}."))
        story.append(Spacer(1, 6 * mm))

    # ---------------------------------------------------------------- decisions
    decisions = list(meeting.decisions.all())
    if decisions:
        story.append(Paragraph("Decisions", styles["H1"]))
        story.append(HRFlowable(width="100%", thickness=0.8, color=BORDER, spaceAfter=6))
        for decision in decisions:
            story.append(Paragraph(decision.content, styles["Bullet"], bulletText="✓"))
        story.append(Spacer(1, 6 * mm))

    # ------------------------------------------------------------- participants
    participants = [
        link.person for link in MeetingParticipant.objects.filter(meeting=meeting)
        .select_related("person")
    ]
    if participants:
        story.append(Paragraph("Participants", styles["H1"]))
        story.append(HRFlowable(width="100%", thickness=0.8, color=BORDER, spaceAfter=6))
        names = ", ".join(p.full_name for p in participants)
        story.append(Paragraph(names, styles["Body"]))
        story.append(Spacer(1, 6 * mm))

    # ------------------------------------------------------------ assigned tasks
    tasks = list(meeting.tasks.select_related("person").all())
    story.append(Paragraph("Assigned Tasks", styles["H1"]))
    story.append(HRFlowable(width="100%", thickness=0.8, color=BORDER, spaceAfter=6))
    if tasks:
        header = [Paragraph(h, styles["HeaderCell"]) for h in
                  ("Person", "Department", "Task", "Deadline", "Status")]
        rows = [header]
        for task in tasks:
            person = task.person.full_name if task.person else (task.mentioned_name or "Unassigned")
            department = task.person.department if task.person and task.person.department else "—"
            deadline = task.deadline.strftime("%b %d, %Y") if task.deadline else "—"
            rows.append([
                Paragraph(person, styles["TaskCell"]),
                Paragraph(department, styles["TaskCell"]),
                Paragraph(task.task, styles["TaskCell"]),
                Paragraph(deadline, styles["TaskCell"]),
                Paragraph(task.get_status_display(), styles["TaskCell"]),
            ])
        table = Table(rows, colWidths=[38 * mm, 32 * mm, 62 * mm, 30 * mm, 26 * mm], repeatRows=1)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), INDIGO),
                    ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        story.append(table)
    else:
        story.append(Paragraph("No tasks were assigned in this meeting.", styles["Body"]))

    # ------------------------------------------------------------- references
    mentions = list(meeting.mentions.select_related("person").all())
    if mentions:
        story.append(Spacer(1, 8 * mm))
        story.append(Paragraph("People Mentioned", styles["H1"]))
        story.append(HRFlowable(width="100%", thickness=0.8, color=BORDER, spaceAfter=6))
        for mention in mentions:
            resolved = mention.person.full_name if mention.person else f"{mention.full_name} (unresolved)"
            story.append(Paragraph(f"• {resolved}", styles["Bullet"]))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buffer.getvalue()
